#include <stdint.h>
#include <string.h>

extern uint32_t _estack, _sidata, _sdata, _edata, _sbss, _ebss;

int main(void);

void Reset_Handler(void) {
  // Copy initialised data from flash and zero .bss before entering main().
  memcpy(&_sdata, &_sidata, (size_t)((char*)&_edata - (char*)&_sdata));
  memset(&_sbss, 0, (size_t)((char*)&_ebss - (char*)&_sbss));

  // The F401 has an FPU and we build with -mfloat-abi=hard: grant CP10/CP11
  // full access before any floating-point instruction runs.
  volatile uint32_t* const SCB_CPACR = (uint32_t*)0xE000ED88;
  *SCB_CPACR |= (0xFu << 20);

  main();
  for (;;) {
  }
}

void Default_Handler(void) {
  for (;;) {
  }
}

// Minimal vector table: initial stack pointer, reset, then the core faults.
// A full project (e.g. generated by STM32CubeMX) lists every peripheral IRQ.
typedef void (*vector_t)(void);
__attribute__((section(".isr_vector"),
               used)) static const vector_t vectors[] = {
    (vector_t)&_estack,  // initial stack pointer
    Reset_Handler,       // reset
    Default_Handler,     // NMI
    Default_Handler,     // HardFault
    Default_Handler,     // MemManage
    Default_Handler,     // BusFault
    Default_Handler,     // UsageFault
};
