#include <cstdint>
#include <cstring>

extern "C" {
extern std::uint32_t _bss_start, _bss_end;
// Generated by the compiler for global constructors; see esp32.ld.
extern void (*__init_array_start[])();
extern void (*__init_array_end[])();

void call_start_cpu0();
}

int main();

namespace {

constexpr std::uintptr_t kRtcCntlBase = 0x3ff48000;
constexpr std::uintptr_t kTimg0Base = 0x3ff5f000;

// Watchdog config registers are write-protected unless this key is written.
constexpr std::uint32_t kWdtWriteKey = 0x50d83aa1;
constexpr std::uint32_t kWdtEnable = 1u << 31;

void wdt_disable(std::uintptr_t config0, std::uintptr_t wprotect,
                 std::uint32_t flashboot_en) {
  auto &cfg = *reinterpret_cast<volatile std::uint32_t *>(config0);
  auto &lock = *reinterpret_cast<volatile std::uint32_t *>(wprotect);
  lock = kWdtWriteKey;
  cfg = cfg & ~(kWdtEnable | flashboot_en);
  lock = 0;
}

}  // namespace

// The ROM calls this once it has copied the image into RAM. It runs on the
// ROM's stack with interrupts off and the CPU on the 40 MHz crystal.
void call_start_cpu0() {
  std::memset(&_bss_start, 0,
              static_cast<std::size_t>(&_bss_end - &_bss_start) *
                  sizeof(std::uint32_t));

  // When booting from flash the ROM arms the RTC watchdog and Timer Group 0's
  // watchdog ("flashboot protection"); they would reset the chip in ~1 s.
  wdt_disable(kRtcCntlBase + 0x8c, kRtcCntlBase + 0xa4, 1u << 10);
  wdt_disable(kTimg0Base + 0x48, kTimg0Base + 0x64, 1u << 14);

  // Run constructors of global C++ objects.
  for (auto *ctor = __init_array_start; ctor != __init_array_end; ++ctor) {
    (*ctor)();
  }

  main();
  for (;;) {
  }
}
