#include <cstdint>
#include <cstring>

extern "C" {
extern std::uint32_t _estack, _sidata, _sdata, _edata, _sbss, _ebss;
// Generated by the compiler for global constructors; see the linker script.
extern void (*__init_array_start[])();
extern void (*__init_array_end[])();

void Reset_Handler();
void Default_Handler();
}

int main();

void Reset_Handler() {
  // Copy initialised data from flash and zero .bss before entering main().
  std::memcpy(
      &_sdata, &_sidata,
      static_cast<std::size_t>(&_edata - &_sdata) * sizeof(std::uint32_t));
  std::memset(
      &_sbss, 0,
      static_cast<std::size_t>(&_ebss - &_sbss) * sizeof(std::uint32_t));

  // Run constructors of global C++ objects.
  for (auto* ctor = __init_array_start; ctor != __init_array_end; ++ctor) {
    (*ctor)();
  }

  main();
  for (;;) {
  }
}

void Default_Handler() {
  for (;;) {
  }
}

// Minimal vector table: initial stack pointer, reset, then the Cortex-M0+'s
// two core faults. TI's startup_mspm0l222x_gcc.c (MSPM0 SDK) lists every
// peripheral IRQ.
using Vector = void (*)();
__attribute__((section(".isr_vector"), used)) static const Vector vectors[] = {
    reinterpret_cast<Vector>(&_estack),  // initial stack pointer
    Reset_Handler,                       // reset
    Default_Handler,                     // NMI
    Default_Handler,                     // HardFault
};
