#include <cstdint>
#include <cstring>

extern "C" {
extern std::uint32_t _estack, _sidata, _sdata, _edata, _sbss, _ebss;
// Generated by the compiler for global constructors; see the linker script.
extern void (*__init_array_start[])();
extern void (*__init_array_end[])();

void Reset_Handler();
void Default_Handler();
}

int main();

void Reset_Handler() {
  // Copy initialised data from flash and zero .bss before entering main().
  std::memcpy(
      &_sdata, &_sidata,
      static_cast<std::size_t>(&_edata - &_sdata) * sizeof(std::uint32_t));
  std::memset(
      &_sbss, 0,
      static_cast<std::size_t>(&_ebss - &_sbss) * sizeof(std::uint32_t));

  // The F401 has an FPU and we build with -mfloat-abi=hard: grant CP10/CP11
  // full access before any floating-point instruction runs.
  *reinterpret_cast<volatile std::uint32_t*>(0xE000ED88) |= (0xFu << 20);

  // Run constructors of global C++ objects.
  for (auto* ctor = __init_array_start; ctor != __init_array_end; ++ctor) {
    (*ctor)();
  }

  main();
  for (;;) {
  }
}

void Default_Handler() {
  for (;;) {
  }
}

// Minimal vector table: initial stack pointer, reset, then the core faults.
// A full project (e.g. generated by STM32CubeMX) lists every peripheral IRQ.
using Vector = void (*)();
__attribute__((section(".isr_vector"), used)) static const Vector vectors[] = {
    reinterpret_cast<Vector>(&_estack),  // initial stack pointer
    Reset_Handler,                       // reset
    Default_Handler,                     // NMI
    Default_Handler,                     // HardFault
    Default_Handler,                     // MemManage
    Default_Handler,                     // BusFault
    Default_Handler,                     // UsageFault
};
